### DISCUSSION TITLE
Manage more advanced `adds`

### DISCUSSION THREAD

**Discussion by taorepoara** [lenra-io/dofigen#11] [Ideas]
In order to be more permissive with the `adds` commands a more advanced structure could be defined instead of string.

```yaml
adds:
- source: myfile.yml
  destination: /tmp/my/full/path.yml
```

The string value will be equivalant to defining the structure with the `source` as the string value and the `destination` as `./`, that will copy the source to the workdir.

We may use the [serde_traitobject](https://docs.rs/serde_traitobject/0.2.7/serde_traitobject/) crate to deserialize the elements.
