### DISCUSSION TITLE
Target platform management

### DISCUSSION THREAD

**Discussion by taorepoara** [lenra-io/dofigen#192] [Ideas]
It would be nice to add target platform specifications in order to make it simpler to manage.

https://docs.docker.com/build/building/multi-platform/

Here is an example of a Rust compilation Dofigen file:

```yaml
---
builders:
- name: builder
  image: ekidd/rust-musl-builder
  adds:
  - "."
  platform:
    linux/amd64:
      env:
        build_target: x86_64-unknown-linux-musl
    linux/arm64:
      env:
        build_target: aarch64-unknown-linux-musl
  script:
  # Build with musl to work with scratch
  - cargo build --release -F cli --target=${build_target}
  # copy the generated binary outside of the target directory. If not the other stages won't be able to find it since it's in a cache volume
  - mv target/${build_target}/release/dofigen ../
  caches:
  # Cargo cache
  - /home/rust/.cargo
  # build cache
  - /home/rust/src/target
image: scratch
workdir: /app
artifacts:
- builder: builder
  source: "/home/rust/dofigen"
  destination: "/bin/"
entrypoint: 
- /bin/dofigen
cmd:
- --help
context:
- "/src"
- "/Cargo.*"
```

Maybe defining env vars could be a first step (like it's done above), but we could think about having also `run` definitions but we must think about how to integrate it:  it runs before, after or instead the original `run`
