### ISSUE TITLE
[Task] Extend external definitions

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#180]
## What should be done 
It would be nice to make the configuration extend another Dofigen configuration by defining the path to this file. File path could be an URL.

I think that it would be nice to do it in builders two.

Here is an example:

springboot-maven.dofigen.yml

```yaml
builders:
  - name: maven-builder
    from: maven:3.9-eclipse-temurin-17-alpine
    workdir: /app
    add:
      - "."
    root:
      run:
        - mvn package -DskipTests
        - mv target/*.jar app.jar
      cache:
        - /root/.m2
        - /app/target
from: eclipse-temurin:17-jre-alpine
artifacts:
  - builder: maven-builder
    source: /app/app.jar
    target: app.jar
cmd: ["java","-jar","app.jar"]
context:
  - /pom.xml
  - /src/main/
```

dofigen.yml

```yaml
extends: springboot-maven.dofigen.yml
```

## Technical recommandation

The extends configuration should be a list of file (but could be define as a direct value).

Load the files from path or URL and parse it. Then merge the files into a single definition.
 
I think that list elements should be extendable by defining symbol (`+` ou `@`) were the current value should be added.

An configuration can be added to a builder. It's also possible to extend only a builder with the next syntax: `extends: myfile.yml/build-name`

Avoid extending loops.

## Ecological concerns

Keep cache on external files to avoid multiple loads of a single file.
