### ISSUE TITLE
[Task] Manage arguments and labels

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#191]
## What should be done 

Add the Dockerfile [`ARG`](https://docs.docker.com/reference/dockerfile/#arg) and [`LABEL`](https://docs.docker.com/reference/dockerfile/#label) commands to manage build arguments and image labels.

Also add `copy` alias for `add`, and `expose` alias for `ports`.

## Technical recommandation

Add the management of Dockerfile `ARG` keyword by defining a map of the arguments with optional value.

```yaml
from: scratch
arg:
  test: my value
  another:
```

Add the management of Dockerfile `LABEL` keyword by defining a map of labels with there values.

```yaml
from: scratch
label:
  test: my value
  another: my other value
```
