### ISSUE TITLE
[Bug]: multiple line command don't add slashes at the end of the dockerfile

### ISSUE THREAD

**Issue by shiipou** [lenra-io/dofigen#196]
### What happened?

With this config : 
```yml
image: nginx:latest
workdir: /web
adds:
- '.'
user: 0
root:
  script:
  - mkdir -p /etc/nginx/templates
  - |
    for file in "$(find ./nginx/docker/ -type f)"; do
      mv "$file" "/etc/nginx/templates/$(basename "$file").template"
    done
```

Dofigen generate this Dockerfile : 

```Dockerfile
RUN mkdir -p /etc/nginx/templates && \
        for file in "$(find ./nginx/docker/ -type f)"; do
  mv "$file" "/etc/nginx/templates/$(basename "$file").template"
done
```

We must have this one : 
```Dockerfile
RUN mkdir -p /etc/nginx/templates && \
        for file in "$(find ./nginx/docker/ -type f)"; do \
		  mv "$file" "/etc/nginx/templates/$(basename "$file").template" \
		done
```

### Version

1.4.0
