### ISSUE TITLE
Handle LABEL

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#251]
## What should be done 

Implement [`LABEL` command](https://docs.docker.com/reference/dockerfile/#label) in the global Dofigen config scope.

A label can be defined by full name like this:

```yaml
label:
  org.opencontainers.image.author: taorepoara
```

Or by name sub parts:

```yaml
label:
  org.opencontainers.image:
    author: taorepoara
    image:
      name: lenra/dofigen:2
      digest: ....
```

## Technical recommandation

Add a `label` field in the Dofigen struct of type `HashMap<String, Value>`.

Implement the generation of the single line `LABEL` command from the previous field.

## Is this task linked with any other ?

Defining the [author label](https://docs.docker.com/reference/dockerfile/#maintainer-deprecated) should be a good practice: #252

<sub><a href="https://huly.app/guest/lenra?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmM1N2E1MTI3NDVhNTE5YTJmMGM1NmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVibmVzcXdpLWxlbnJhLTY2YzQ1NjEwLWEwZmY2MDljODEtYzQyZjYxIiwicHJvZHVjdElkIjoiIn0.wZYknUqCXVJKQH27i8pqjrAyRjX559Ela9aJxqjriZY">Huly&reg;: <b>DOFIG-248</b></a></sub>
