### ISSUE TITLE
[Bug]: VecPatch add command needs a list

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#274]
### What happened?

I used defined a context to patch an extended one like this:

```yaml
extend: anotherfile.yml
context:
  +: MyFile
```

This resulted to a deserialization error (see Relevant log output).
This works fine with the next value:
```yaml
extend: anotherfile.yml
context:
  +: 
    - MyFile
```

Deserialization should accept one or many elements.

### Version

2.0.0

### Relevant log output

```Shell
Could not deserialize resource File("dofigen.yml"): data did not match any variant of untagged enum VecPatchDeserializable
```
