### ISSUE TITLE
[Bug]: Integer chmod is not interpreted

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#281]
### What happened?

I defined a chmod field on a copy, but Dofigen react like the field was not present.

Here is an example:

```yaml
copy:
  source: "."
  target: "."
  chmod: 555
```

The expected behavior is to interpret that value just like `"555"`.

### Version

2.0.0
